import Foundation

class MockedAppleReposStorage {
    var appleRepos: [AppleRepos] = [AppleRepos(id: 1, fullName: "Repos 1", isPrivate: true),
                                    AppleRepos(id: 2, fullName: "Repos 2", isPrivate: true),
                                    AppleRepos(id: 3, fullName: "Repos 3", isPrivate: true),
                                    AppleRepos(id: 4, fullName: "Repos 4", isPrivate: true),
                                    AppleRepos(id: 5, fullName: "Repos 5", isPrivate: true),
                                    AppleRepos(id: 6, fullName: "Repos 6", isPrivate: true),
                                    AppleRepos(id: 7, fullName: "Repos 7", isPrivate: true),
                                    AppleRepos(id: 8, fullName: "Repos 8", isPrivate: true),
                                    AppleRepos(id: 9, fullName: "Repos 9", isPrivate: true),
                                    AppleRepos(id: 10, fullName: "Repos 10", isPrivate: true),
                                    AppleRepos(id: 11, fullName: "Repos 11", isPrivate: true),
                                    AppleRepos(id: 12, fullName: "Repos 12", isPrivate: true),
                                    AppleRepos(id: 13, fullName: "Repos 13", isPrivate: true),
                                    AppleRepos(id: 14, fullName: "Repos 14", isPrivate: true),
                                    AppleRepos(id: 15, fullName: "Repos 15", isPrivate: true),
                                    AppleRepos(id: 16, fullName: "Repos 16", isPrivate: true),
                                    AppleRepos(id: 17, fullName: "Repos 17", isPrivate: true),
                                    AppleRepos(id: 18, fullName: "Repos 18", isPrivate: true),
                                    AppleRepos(id: 19, fullName: "Repos 19", isPrivate: true),
                                    AppleRepos(id: 20, fullName: "Repos 20", isPrivate: true),
                                    AppleRepos(id: 21, fullName: "Repos 21", isPrivate: true),
                                    AppleRepos(id: 22, fullName: "Repos 22", isPrivate: true),
                                    AppleRepos(id: 23, fullName: "Repos 23", isPrivate: true),
                                    AppleRepos(id: 24, fullName: "Repos 24", isPrivate: true),
                                    AppleRepos(id: 25, fullName: "Repos 25", isPrivate: true),
                                    AppleRepos(id: 26, fullName: "Repos 26", isPrivate: true),
                                    AppleRepos(id: 27, fullName: "Repos 27", isPrivate: true),
                                    AppleRepos(id: 28, fullName: "Repos 28", isPrivate: true),
                                    AppleRepos(id: 29, fullName: "Repos 29", isPrivate: true),
                                    AppleRepos(id: 30, fullName: "Repos 30", isPrivate: true),
                                    AppleRepos(id: 31, fullName: "Repos 31", isPrivate: true),
                                    AppleRepos(id: 32, fullName: "Repos 32", isPrivate: true),
                                    AppleRepos(id: 33, fullName: "Repos 33", isPrivate: true),
                                    AppleRepos(id: 34, fullName: "Repos 34", isPrivate: true),
                                    AppleRepos(id: 35, fullName: "Repos 35", isPrivate: true),
                                    AppleRepos(id: 36, fullName: "Repos 36", isPrivate: true),
                                    AppleRepos(id: 37, fullName: "Repos 37", isPrivate: true),
                                    AppleRepos(id: 38, fullName: "Repos 38", isPrivate: true),
                                    AppleRepos(id: 39, fullName: "Repos 39", isPrivate: true),
    ]
}
